version: '3.8'

services:
  voxtral-streaming:
    build: .
    ports:
      - "8000:8000"  # UI + WebSocket
      - "8005:8005"  # Health Check
      - "8766:8766"  # TCP Server
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024
      - OMP_NUM_THREADS=8
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./logs:/app/logs
      - ./model_cache:/app/model_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  model_cache:
  logs:
