name: Test Voxtral Streaming

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev libasound2-dev libsndfile1-dev ffmpeg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest tests/ -v --tb=short
    
    - name: Test imports
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -c "from src.models.audio_processor_realtime import AudioProcessor; print('✅ AudioProcessor import OK')"
        python -c "from src.models.voxtral_model_realtime import VoxtralModel; print('✅ VoxtralModel import OK')"
        python -c "from src.utils.logging_config import logger; print('✅ Logging config OK')"
        python -c "from src.utils.config import config; print('✅ Config OK')"
        python -c "from src.models.audio_processor import AudioProcessor; print('✅ Legacy AudioProcessor import OK')"
        python -c "from src.models.voxtral_model import VoxtralModel; print('✅ Legacy VoxtralModel import OK')"
